### PR TITLE
Bugfix/266 toggle instance in pyblish pype crashes

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
Issue:
`setData` method called in model cause `TypeError: invalid result from InstanceItem.setData()`

Solution:
Toggle setData method happens on item not on model.

Resolves: https://github.com/pypeclub/pype/issues/266

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
This should be fixed in pyblish-lite too for client without 2.10 release.

**Comment by iLLiCiTiT** [comment]
> Not sure whether its related to this, but the callback instanceToggled does not seem to work.

That is not related, but good to know. Just look how it's implemented in pyblish-qml and it should be easy to implement here if necessary in next PR. But I don't see use case for that to be honest?

**Comment by tokejepsen** [comment]
> But I don't see use case for that to be honest?

For example in Harmony you can persist the publish state to the scene so anyone picking up the scene afterwards will have the same enabled/disabled instances.
In Harmony this is done thought enabling/disabling nodes in the view.

**Comment by iLLiCiTiT** [comment]
> In Harmony this is done thought enabling/disabling nodes in the view.

Create new issue, it should be easy to do.

**Pull request merged**
