### PR TITLE
Nuke render write targeting knob improvement

### PR DESCRIPTION
**Pull request by jezscha**
reaction on comunity sugestion:

Jiri Sindelar09/25/2020
Sorry to highjack the thread, but new users always find this node confusing. It would be great to not only allow to publish on the farm with render already done, but also have a more self explanatory UI. Not sure if it is easy to make radio buttons with Avalon Nuke, what about dropdowns?
Render dialog Suggestion
image

### CODE REVIEW

**Comment by tokejepsen** [comment]
If you can submit to the farm without having "Publish" enabled then we dont need the "Publish" dropdown.

Also "Remote" might be a better parity to "Local", instead of "Farm".

**Comment by mkolar** [comment]
I would change the first option to be more explicit. Just so someone doesn't think they are not actually publishing renders.

```
Render: Use existing frames
        Local
        On farm
```

>Also "Remote" might be a better parity to "Local", instead of "Farm".

I'd prefer `On farm` as @jezscha did it. It's universally used in the industry for this, while remote suggests more of a different location. We already have clients that use local and remote render farm for instance. I'd like to keep it open for adding more options like this later maybe.

regarding the `publish` dropdown. I don't think we need it at all actually. If you're rendering locally, the publish happens there too, while if you send to farm, the publish automatically happens there as well. Maybe I'm just missing the point somewhere?

**Review by mkolar — CHANGES_REQUESTED** [review]
The new system works fine, however, we need to convert the old one to legacy collector and repair. The same as when we updated this process last time. I think it's safe to say, that we don't need 2 legacy processes, so I would replace the existing `collect_legacy_write.py` with collecting write nodes that have the old type of render target selector. 

`validate_write_legacy` should flag these old nodes and then repairs them by recreating them with the new attributes.

**Comment by jezscha** [comment]
> The new system works fine, however, we need to convert the old one to legacy collector and repair. The same as when we updated this process last time. I think it's safe to say, that we don't need 2 legacy processes, so I would replace the existing `collect_legacy_write.py` with collecting write nodes that have the old type of render target selector.
> 
> `validate_write_legacy` should flag these old nodes and then repairs them by recreating them with the new attributes.

The legacy detector is implemented for both types now older and old.

**Pull request merged**
