### PR TITLE
Next task update with settings

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changes
- rewritten `NextTaskUpdate` to be able use project settings

## TODO
- [x] Define next task status in settings
    - **now** set status to hardcoded status name `"Ready"`
    - **now** status is not set if next task/s don't have status `"Not Ready"`
    - **suggest n1** add to settings mapping `from` ("Not ready") -> `to` ("Ready", others, ...)
        - I think that should be enough
    - **suggest n2** set next task status based on task type
        - that would be more complex to set
- [x] Define ignored statuses
    - status names that skip check of status state
    - if task has one of these statuses it is (for logic in handler) like it's status state is `"Done"` (e.g. status `"Omitted"`)

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
> Define next task status in settings

Used `suggestion n1`

**Comment by iLLiCiTiT** [comment]
Suggested feature by @mkolar
- set next task status based on Task type id (like it is) and sorted by name
    - if there are multiple tasks with same type id only one will change status

**Comment by iLLiCiTiT** [comment]
> set next task status based on Task type id (like it is) and sorted by name

Done, it will require to explain how it works in settings label. I couldn't summarize it to words even I would understand.

**Comment by mkolar** [comment]
Name sorting works well
We are currently ensuring that all previous tasks are `complete` before we allow changing status on the following tasks. That, however, causes problems if those are not strictly linear. I'd change this to only require all tasks within the same `type` to be completed, before allowing the following task trigger. 

For example on this image. We should trigger `rigging` task when "modelling_body" gets approved. However currently we also require the `art` task to be approved, before rigging is set to "ready"
image

**Review by mkolar — CHANGES_REQUESTED** [review]
need to tweak the logic based on previous commnet

**Comment by iLLiCiTiT** [comment]
> need to tweak the logic based on previous commnet

Now should work like expected.

**Additional question:**
When "Name sorting" is turned on, handler does not care about any previous tasks **even from same task type**. Should care at least about same task type?

**Comment by mkolar** [comment]
> When "Name sorting" is turned on, handler does not care about any previous tasks even from same task type. Should care at least about same task type?

I think for now it's ok to keep it simple as it is, but there is certainly more logic needed at some point.

**Review by mkolar — APPROVED** [review]

**Pull request merged**
