### PR TITLE
Pype: Frozen code improvements

### PR DESCRIPTION
**Pull request by antirotor**
## Intro

There were major roadblocks to make frozen pype to work, biggest of them was that **.zip** archive doesn't actually work as parts (like avalon-core) read files from there, not just import them.

### Changes:

- Pype entry point was renamed from `pype.py` to `start.py` to avoid confusion with pype module and with similar philosophy as `setup.py`, `build.ps1` etc.
- Build now produce two executables - `pype.exe` - Win32 GUI application that has no console attached and `pype_console.exe` that has console and print out stuff to it.
- Running process has now available `PYPE_EXECUTABLE` environment variable pointing to either `pype.exe` or `pype_console.exe` or `python` in *venv* when run from live sources.
- There is now `PYPE_VERSION` environment variable that can be used with `PYPE_ROOT` to identify running Pype version.
- Pype will now install itself as directory in user data dir. It will search for zips and directories to find out latest version.
- Zips produced from detected sources will exclude stuff like `.git` files and other unnecessary things under Pype repository.
- Introducing tools scripts in `tools`:
   - `create_env` - this will **clean** and (re)create virtual environment in `./venv` based on *requirements.txt*
   - `build` - this will **clean** `builld` directory and build pype there. You can find `./build/build.log` with latest output.
   - `create_zip` - this will create pype zip from currently running sources. When run with `--path` option, it will create zip in specified directory, otherwise it will put it directly to user data dir where **Igniter** will find it.
   - `make_docs` - update sphinx api documentation sources and build html documentation in `./docs/build`
   - `run_mongo` - run local mongodb instance for developers
   - `run_settings` - run settings UI in dev mode
   - `run_tests` - run pytest
   - `run_tray` - run tray
- Moved [acre](https://github.com/BigRoy/acre) and [pyblish-base](https://github.com/pyblish/pyblish-base) to virtual environment and those are deleted from submodules. See below for more info.
- Adding `run` command to pype, accepting one argument - script path and passing rest as arguments to it.
- Added `--use-staging` option to prefer *staging* over *production* version. Specifying it will use latest staging available.
- When two Pype version are detected - one is zip file and one in directory - directory will take precedence.
- Minor bug fixes.

To overcome problems with **cx_freeze** and .pyc files in different python interpreters there is now one more step during build process. After build is done, script `tools/buid_dependencies.py` is run, copying content of `venv/Lib/site-packages` to builds `dependencies` and deleting duplicates from builds `lib`.

### Run command:

`run` command allow to run scripts by Pype in its environment. Simple use:

```shell
pype_console.exe run /path/to/script.py -o1 --option2 arg1 arg2
```
This will run `/path/to/script.py` in Pype context and pass it options and arguments in `sys.argv`

Using it in conjunction with `PYPE_EXECUTABLE` environment variable from within code:
```python
import os
import subprocess

result = subprocess.run(
    [os.getenv("PYPE_EXECUTABLE"), "run", "/path/to/script", "some", "arguments"])
```

### Git info:

As **acre** and **pyblish-base** are removed from submodules, there are few steps necessary in existing repositories. You can either clone again, or follow these steps:

* Delete *acre* and *pyblish-base* sections from `.gitmodules` file
* Stage `.gitmodules` - `git add .gitmodules`
* Delete *acre* and *pyblish-base* sections from`./.git/config`
* Run:
```shell
git rm --cached .\repos\acre
git rm --cached .\repos\pyblish-base
```
* Commit changes
* Delete submodule directories

### Version resolution

❕ **WARNING:**
Pype is by default ignoring **staging** variants. When `--use-staging` argument is used, Pype will look for **staging** variants ignoring non-staging.

#### Version resolution works like this:

1.2.3 < 1.2.3-client
1.2.3-staging < 1.2.3
1.2.3-client-staging < 1.2.3-client

| 🏴  **Warning:** it is implementing #849 and #850 |
| --- |

### CODE REVIEW

**Comment by mkolar** [comment]
after succesfull venv installation we still have build issues. This was a fresh clone and it looks like build expects `build` folder to already exist

image

**Comment by antirotor** [comment]
> after succesfull venv installation we still have build issues. This was a fresh clone and it looks like build expects `build` folder to already exist
> 
I always thought we have `build` directory in repository but we don't. Added checks for that and it will be created when missing.

**Comment by antirotor** [comment]
Damn it, running frozen code still gives me this. Any idea @iLLiCiTiT ?

```
... running: C:\Users\annatar\AppData\Local\pypeclub\pype\pype-v3.0.0\pype\pype\modules\ftrack/ftrack_server/sub_user_server.py 10021
!!! Pype crashed:
Traceback (most recent call last):
  File "start.py", line 458, in boot
    cli.main(obj={}, prog_name="pype")
  File "E:\projects\pype\pype-3\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "E:\projects\pype\pype-3\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "E:\projects\pype\pype-3\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\projects\pype\pype-3\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\projects\pype\pype-3\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:/Users/annatar/AppData/Local/pypeclub/pype/pype-v3.0.0/pype\pype\cli.py", line 297, in run
    runpy.run_path(script, run_name="__main__", )
  File "C:\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\annatar\AppData\Local\pypeclub\pype\pype-v3.0.0\pype\pype\modules\ftrack/ftrack_server/sub_user_server.py", line 5, in <module>
    from ftrack_server import FtrackServer
ModuleNotFoundError: No module named 'ftrack_server'
```

**Comment by iLLiCiTiT** [comment]
Seems like it didn't add directory of the script to sys path (which worked when I tested it). `ftrack_server` is python file next to the `sub_user_server.py` script. I can take a look tomorrow.

**Comment by iLLiCiTiT** [comment]
@antirotor changed `from ftrack_server import FtrackServer` to `from pype.modules.ftrack.ftrack_server.ftrack_server import FtrackServer` so it works now

**Comment by antirotor** [comment]
❕ **IMPORTANT**: `PYPE_MODULE_ROOT` is gone. Use `PYPE_REPOS_ROOT` to point to where acre, avalon-core, etc. resides.

**Review by mkolar — APPROVED** [review]
There are still caveats to solve, but let's merge to unblock other development

**Pull request merged**
