### PR TITLE
Nuke: deadline submission with search replaced env values from preset

### PR DESCRIPTION
**Pull request by jezscha**
there might be a occasions where anyone would need to search replace any environment values. This will add ability to add dictionary with pairs to presets which are then iterated on each environment value.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Sorry, what is the use case for this?

Thought we wanted to move towards explicit environment variables on Deadline submission to avoid implicit troubleshooting?

**Comment by mkolar** [comment]
This shouldn't make it into an official release. It is a situational patch for a client and we need to find a better way to deal with it in 3.0.

the problem is that we need different environment values on certain keys, for jobs on the farm vs workstations. Normally we just send the workstation environments, but here it's simply not enough and some things need to be re-mapped. 

@jezscha I assume that the colourspace change, made it here by accident? that should be a second PR

**Review by mkolar — CHANGES_REQUESTED** [review]
PR is a mix of two features, one of which should stay just in a local deployment. Let's split it please

**Comment by jezscha** [comment]
> PR is a mix of two features, one of which should stay just in a local deployment. Let's split it, please

that had been reversed so this PR is holding only one feature fix. The other had been moved to #1199

**Comment by jezscha** [comment]
> Sorry, what is the use case for this?
> 
> Thought we wanted to move towards explicit environment variables on Deadline submission to avoid implicit troubleshooting?  Yes, you're right, I had enhanced the process. Thanks for reminding me ;)

**Pull request merged**
