### PR TITLE
[draft] Feature/135 web socket server

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
Basic implementation of websocket server without any functionality ATM.

Websocket server is based on Namespaces. Each namespace has endpoint which is for determination which callback is used. Namespace with endpoint "/my_namespace" will means that it's callbacks are used when client is connected to "ws:/localhost:{PORT}/my_namespace". Each namespace can define 3 callbacks `new_client` when new client created session, `client_left` when client close sesison and `on_message` when client send message. It is possible to send message back to each client at any time.

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
For this feature is used python-websocket-server which is installable via pip but contain really old version. Wanted to create PR into pype-setup but pip version is heavily outdated so I'll probably add module into vendor.

**Comment by antirotor** [comment]
if it depends on https://github.com/Pithikos/python-websocket-server then I am little afraid of how this code is maintained. If you follow Issues there it seems to be dead.

**Comment by iLLiCiTiT** [comment]
> If you follow Issues there it seems to be dead.

Yes, It's half dead. Advantage of this "module", if we can call it module, is that it contains one file with 400 lines. Most of those lines are overriden in server.py and are easy to modify (400 lines). This is the simplest implementation with single use case: Communication with hosts. It's not for global server usage, this server run in tray and only for localhost.

All other modules giving this ability has more than 10MB and are so massive it's actually hard to implement "simple" solution.

**Comment by antirotor** [comment]
>  can't be stopped with python code on Windows and required force killing process to stop it

But that could be helped using this: https://github.com/cjrh/aiorun#id7 - seems like you can send CTRL+C / CTRL+BREAK signals to do it. Not that elegant, but it should work and I like `websockects` modern asyncio concept.

**Comment by iLLiCiTiT** [comment]
> Not that elegant, but it should work and I like websockects modern asyncio concept.

I see, and also like the concept but is a bit problematic. Asyncio concept is not required for this purpose (this is not server which will handle more than 10 connections at one time). The `aiorun` is based on Python 3.8 features (if I was looking good) and still is not perfect. I have to be able to kill the thread where server is running without killing whole application...

**Comment by antirotor** [comment]
I suppose we could maintain 400 line of code in case something will not work...

**Comment by iLLiCiTiT** [comment]
That was actually my idea.

First I've tried `websockets` which was great easy to work module, until I tested on windows. I asked the author if he know about solution for windows and he answered that he don't care much about windows and reminded me that it is python's bug not bug of the module.

Then I wanted to use `Tornado` or `autobahn` but I've found out they are really massive f*cking frameworks for all types of communication and all possible cases. I wasn't able to create so simple version of websocket server using them, with control we need for tray "service".

Then I've tried some smaller alive projects but all of them had limitations we may need and were based on same code as Pithioks' websocker. So when I found out it is so simple it is easy to modify for our purpose, I've choose it.

**Comment by iLLiCiTiT** [comment]
Yesterday I found this https://python-socketio.readthedocs.io/en/latest/server.html. Haven't tried it yet but seems to have both async and thread based server with HTTP. WS server has already implemented event based system (or it looks like that). That may be better if server has ability to be terminated without killing whole process.

**Comment by antirotor** [comment]
that one looks really good, full of features, supporting lot of stuff and yet seems simple enough. Event could be utilized to control server state. Nice.

**Comment by mkolar** [comment]
decided to go different path. closing this

**Pull request closed without merging**
