### PR TITLE
Bugfix/264 pyblish pype is too slow with 10 instances

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
Widget for log detail is not set automatically but after expanding.

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
I will try one more enhancement.

If that won't work I have backup solution to skip debug + info logs when more than 15 instances being processed.

**Comment by tokejepsen** [comment]
Tried it again, and it still slows down to a halt.

**Comment by iLLiCiTiT** [comment]
Added button to skip logs. 
image

**Comment by tokejepsen** [comment]
Skipping logs works!

It even flags validations when skipping logs, so that'll work.

**Pull request merged**
