### PR TITLE
Calculate size

### PR DESCRIPTION
**Pull request by tokejepsen**
- option to only calculate without deletion

### CODE REVIEW

**Comment by mkolar** [comment]
This works well, however if you run this on a bigger stack of versions it might take a while and showing the result in the notification might be missed. Could this be tweaked to show the result in another interface widget that replaces the first one? Ideally it would tell you the size, and user could just continue in removing calculated files. 

@tokejepsen what do you think?

**Comment by tokejepsen** [comment]
I've logged the size as well, so it persistent there. Dunno what the intent of the logging is for the end user?

Only other way would be to display the interface again, but not sure the action handlers are designed for this? @iLLiCiTiT

**Comment by iLLiCiTiT** [comment]
> Only other way would be to display the interface again, but not sure the action handlers are designed for this?

It is possible and there are few approaches for that, all of them must be handled properly... One possible approach is in `action_delete_asset.py`. I can look into that when I'll get back from holiday.

**Comment by tokejepsen** [comment]
Last option is to show a job, which might be good anyways to show progression. The job title could be the size.

**Comment by tokejepsen** [comment]
I might take this logic into a Library Loader instead; https://github.com/pypeclub/pype/issues/396

**Comment by mkolar** [comment]
@tokejepsen @iLLiCiTiT 
I'm happy to merge this and update later on.

**Pull request merged**
