### PR TITLE
Black Magic DaVinci Resolve Host integration

### PR DESCRIPTION
**Pull request by jezscha**
**Overview**
DaVinci Resolve is great tool for editing, color-grading, media management and encoding. 
Adding Resolve into our portfolio of integrated hosts should not be a big issue as most of the functionality has  been written already for Premiere and Hiero. Last couple of years, some useful open source code using Resolve’s python api has been developed which could inspire our development.

**Goals**
- Be able to batch rename clips
- Be able to tag clips with families for further subset definitions in publishing
- Be able to batch export and publish conformed clips into pipeline
- Be able to batch load (integrate) from db subsets to timeline as version managed containers

**Problems**
- app GUI expand-ability limits
- python 3.6 has to be installed on particular place in system
- python 3.7 or higher not supported

**Milestones**
- Project context wrapper [ui]
- Pype menu [menu]
- Tools for batch renaming of clips inspired by Hiero [ui]
- Versioning of clips [timeline>menu>submenu]
- Publishing with Pype into Avalon DB and Ftrack
- Integrating / Loading subsets back to timeline as containerized clips

**Github projects**
https://github.com/Puppetworks-Animation-Studio/deadline-davinci-resolve
https://github.com/veryqiang/footbrake
https://github.com/IgorRidanovic/DaVinciResolve-ExportProjects
https://github.com/Benerman/DaVinci-Resolve-Scripting
https://github.com/pressreset/resutil

**Testing this PR**
A. _Installing Resolve's own python 3.6 interpreter._
DaVinci Resolve is using hard-coded method for searching python path and ignoring what ever is in PATH. Windows is searching for "{LOCALAPPDATA}/Programs/Python/Python36" on mac it is "~/Library/Python/3.6/bin" and linux "/opt/Python/3.6/bin". All of these paths are chosen automatically during Python 3.6 installer. We are using `Python 3.6.2`

B. _Installing PySide2 into python 3.6 for correct gui work:_
1. As Pype is using gui inside Resolve, we need to install own PySide2 into the python 3.6 as it is explained above. Follow this step-by-step:
2. open terminal > windows menu > type `cmd`
3. paste this to terminal > %LOCALAPPDATA%\Programs\Python\Python36\python.exe -m pip install PySide2
4. after installation finished then all is done

C. _Set Resolve's Fusion settings for Python 3.6 interpereter:_
As it is shown in bellow picture you have to go to Fusion Tab and then in Fusion menu find Fusion Settings. Go to Fusion/Script and find `Default Python Version` and swith to Python 3.6

D. _Set correct paths in pype-config_
- set env var **RESOLVE_UTILITY_SCRIPTS_SOURCE_DIR** in `environments\resolve.json` to a real empty directory or just keep the list empty.

E. _In Ftrack on project run Update Custom Attributes_
This will add Resolve launcher into available apps for use on a project
image

F. _In Ftrack on project info panel in Applications attribute select BM DaVinci Resolve 16_
image

G. _In Ftrack on project Actions chose SyncToAvalon action_
image

H. _In Ftrack on project create directory `editorial` and task `conforming`, save the Ftrack to db and repeate G. again_
image

I. _Start BM DaVinci Resolve 16 from actions on the task `conforming`_
image

If you would like to know more about ongoing development just follow this link: https://miro.com/app/board/o9J_kt15XIY=/ 
image

resolving #96 
dependent PR: https://github.com/pypeclub/pype-config/pull/33

### CODE REVIEW

**Comment by mkolar** [comment]
To avoid generating huge PRs, we'll split the development into smaller chunks that are more easily testable. So I would like to wrap up this PR at the point when we have menu loaded (in a simplified way for now) and we can invoke all the GUIs with access to resolve context, save and open workfiles. And at that, this is very successful so far. 

I've followed the steps and have avalon/pype main menu in resolve. Awesome. I can't get it to save workfile though. It simply doesn't do anything. Mind you I'm running free version of resolve while you are on resolve studio so there might be some difference there I suppose.

Of course there is the question of how useful workfiles app actually is in resolve, but the implementation you demoed in person, looks good enough for certain type of production.

**Comment by mkolar** [comment]
I'm getting this in the console, but that is expected considering we don't have external access to resolve context in the free version 
image

**Comment by mkolar** [comment]
I got some traceback from resolve when trying to use `save as` in workfiles
```
*** WRN: >>> { pypeapp.lib.anatomy }: [ Project "milan_testing" does not have his own templates. Trying to use default. ] 
WARNING:pypeapp.lib.anatomy:Project "milan_testing" does not have his own templates. Trying to use default.
Traceback (most recent call last):
  File "C:\code\pype-setup\repos\avalon-core\avalon\tools\workfiles\app.py", line 630, in on_save_as_pressed
    work_file = self.get_filename()
  File "C:\code\pype-setup\repos\avalon-core\avalon\tools\workfiles\app.py", line 571, in get_filename
    session=session)
  File "C:\code\pype-setup\repos\avalon-core\avalon\tools\workfiles\app.py", line 123, in __init__
    self.refresh()
  File "C:\code\pype-setup\repos\avalon-core\avalon\tools\workfiles\app.py", line 224, in refresh
    template = self.get_work_file(template)
  File "C:\code\pype-setup\repos\avalon-core\avalon\tools\workfiles\app.py", line 154, in get_work_file
    current_file = self.host.current_file()
  File "C:\code\pype-setup\repos\pype\pype\resolve\workio.py", line 76, in current_file
    pm = get_project_manager()
  File "C:\code\pype-setup\repos\pype\pype\resolve\lib.py", line 14, in get_project_manager
    self.pm = resolve.GetProjectManager()
AttributeError: 'NoneType' object has no attribute 'GetProjectManager'
```

**Comment by tokejepsen** [comment]
Had a quick go with python and resolve, and that error message about "NoneType" is the issue with the free version.

**Comment by jezscha** [comment]
> I got some traceback from resolve when trying to use `save as` in workfiles
> ...
>   File "C:\code\pype-setup\repos\pype\pype\resolve\lib.py", line 14, in get_project_manager
>     self.pm = resolve.GetProjectManager()
> AttributeError: 'NoneType' object has no attribute 'GetProjectManager'
> ```

It could be a issue of free Resovle. Which is strange as all the processes are running from inside and nothing is subprocessed.

**Comment by jezscha** [comment]
> I'm getting this in the console, but that is expected considering we don't have external access to resolve context in the free version

Yes, this will not work as it is external link to Resolve..

**Comment by tokejepsen** [comment]
If you follow this guide; https://gist.github.com/garyo/c398abc2d3d6f801a61ad86a0f5b651e with python 3.6 installed, you will end up with the same `NoneType` error.

**Comment by tokejepsen** [comment]
.... with the free version of Resolve

**Comment by jezscha** [comment]
> If you follow this guide; https://gist.github.com/garyo/c398abc2d3d6f801a61ad86a0f5b651e with python 3.6 installed, you will end up with the same `NoneType` error.

It would make more sense to use the step by step guide which is part of this PR.. There are some bugs in paths of the guide you had sent.

**Comment by tokejepsen** [comment]
> It would make more sense to use the step by step guide which is part of this PR.. There are some bugs in paths of the guide you've sent.

I'm just saying that its not just an issue about `NoneType` with the guide in the this PR.

**Pull request merged**
