### PR TITLE
Reboot of sphinx api doc

### PR DESCRIPTION
**Pull request by antirotor**
## Problem

API documentation was forgotten for some time and it is time to reboot it and **make it great again!**

## Solution

This PR is first step for doing so. I've fixed few issues that prevented Sphinx to import stuff correctly, but there remain lot of problems that we have to tackle:

* there are obvious syntax errors in docstrings
* there are places where Sphinx autodoc cannot see - mainly publish plugins. I've solved it by converting them to modules (at first only *plugins/maya/publish* are but if it doesn't break anything (and I don't see why it should) we could *modulize* (🙊) the rest.
* autogenerated API is now slighly confusing as there is lots of stuff, so we need to edit rst files and organize the landing page better.

### How to generate it (and see errors in code we need to fix):

1) be sure mongodb is accessible (otherwise it will take massive amount of time as each script tries to connect to it and will timeout
2) be sure you have running tray somewhere (because of rest api)
3) run `.\make_docs.bat`
4) notice lots of red lines in output - all those are basically syntax errors in docstrings
5) find generated result in `docs/build/html/index.html`

if you run into problem with modules not found (specific to host for example like `maya`, add them to **autodoc_mock_imports** at the end of `docs/source/conf.py`.

If you are not sure about syntax or what is wrong with your docstrings, I suggest to install [pydocstyle](https://pypi.org/project/pydocstyle/) and configure your favorite linter to make use of it. You can use both Napoleon style or rst style syntax:

https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

https://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html

Idea is that this PR will become updated by you 👉 dear developers, that you'll take care of your own code. Happy documenting!

### CODE REVIEW

**Comment by tokejepsen** [comment]
Could we maybe make this a CI test? Then its obvious where the docstrings are lacking.

**Comment by antirotor** [comment]
> Could we maybe make this a CI test? Then its obvious where the docstrings are lacking.

We could set Hound to use *pydocstyle* but right now I am afraid it would generate lot of clutter. But later on I am for it. Running Sphinx using CI would be also possible, but right now we need to have avalon and pype running for that process to finish so it wouldn't be trivial process to setup (we could make pype as docker image).

**Comment by mkolar** [comment]
I reckon we should restart this one from fresh develop base now

**Comment by antirotor** [comment]
Closing it as it is replaced by #834

**Pull request closed without merging**
