### PR TITLE
#241 - Implemented pype-config/presets/plugins/test/*

### PR DESCRIPTION
**Pull request by kalisp**
Implemented GUI for automatic test case.
241_test

### CODE REVIEW

**Comment by mkolar** [comment]
Quite frankly I'm not sure this is being used anywhere :D. You're pulling some serious skeletons out here. Blame says it was added by @antirotor about a year ago...

**Comment by kalisp** [comment]
Yeah, I wasn't sure about this one. But an automatic test for this is still present in the code, so this should probably stay too.

**Comment by kalisp** [comment]
Removed dict-form, depends on #525

**Comment by iLLiCiTiT** [comment]
If it's for testing purposes we should not put that into GUI. Values can be in defaults so are still usable for test purposes.

**Comment by kalisp** [comment]
Closing as unneeded/unwanted, defaults already present in `~/defaults/project_settings/plugins`, so tests should be working.

This might be reopened if/when GUI will have functionality to display some parts only in Dev mode.

**Pull request closed without merging**
