### PR TITLE
Feature/180 store task types

### PR DESCRIPTION
**Pull request by kalisp**
Re-creation of broken PR #516
Solves: pypeclub/pype/#180

Currently task info is stored in both project config and assets as list of task names only. This PR enhances it to **list of dictionaries**.

I kept both config and asset as LISTs to follow https://github.com/getavalon/core/pull/556 and it felt wrong to have `project.config.tasks` as a dictionary and `asset.tasks' as a list.
Schemas already expect list of dictionaries, so no change is needed there.
(Could be changed easily if necessary.)

I added task name to short_name mapping. This short_name could be used in paths.. in the future.

Changed do dictionaries.
180_project
180_asset

Changed everywhere I could find that it should be changed. 
Please test it in Nuke. (Maya and Clockify seems fine.)
Inventory app is not showing anything in Maya, but I don't think its a result of this change.

Requires:
pype-config:pypeclub/pype-config#81
avalon-core:pypeclub/avalon-core#196

Resetting queries: (EDIT)
db.getCollection('YOUR_COLLECTION_NAME').updateMany({type:"project"}, {$unset: {"config.tasks":""}})
db.getCollection('YOUR_COLLECTION_NAME').updateMany({type:"asset"}, {$unset: {"data.tasks": ""}})

### CODE REVIEW

**Comment by mkolar** [comment]
the resetting query needs to be 
```
db.getCollection('YOUR_COLLECTION_NAME').updateMany({type:"project"}, {$unset: {"config.tasks":""}})
db.getCollection('YOUR_COLLECTION_NAME').updateMany({type:"asset"}, {$unset: {"data.tasks": ""}})
```
to completely wipe the tasks, otherwise the sync fails

**Comment by mkolar** [comment]
the last thing that seems to be blocking this is broken workfiles app after the change

**Comment by kalisp** [comment]
I don't think that Workfile Save as is result of this change, see https://github.com/pypeclub/avalon-core/commit/c5cc6e1122ffdf2ed461a0786e9d9abbaddd7705 (error message sent: AttributeError: 'list' object has no attribute 'clear')

I found some issues when creating completely new DB though, fixed them.

**Comment by mkolar** [comment]
you're right, it was because this branch was not up to date with develop.

**Pull request merged**
