### PR TITLE
Environments in settings GUI

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
- first version of way how to store environments in setting gui
- this PR allows to set environemnts only via `raw-json` item type
- with key `"env_group_key"` is possible to set "environment group" (`"maya"`, `"maya_2020"`, `"nuke"`, etc.)
    - it is allowed to set only one item with specific `"env_group_key"`
- current implementation kept previous environment values BUT
- values of environment group is overriden if has equivalent in system configs
    - EXAMPLE: if schema will contain `raw-json` item with `"env_group_key": "maya"` and values of this schema will be saved, environments from `~/pype/settings/defauls/environments/maya.json` won't be used anymore and can be removed

### CODE REVIEW

**Review by mkolar — COMMENTED** [review]
saving works fine, but I can't get it to load the environments back. It always only load those that are stored in .json files, but the ones saved via settings are ignored.

**Comment by iLLiCiTiT** [comment]
> but the ones saved via settings are ignored.

Should be fixed. I didn't save environments to studio overrides...

**Comment by mkolar** [comment]
Nope still nothing. It shouldn't be dependent on studio overrides though. Even in default, we want to save some envs into settings

**Comment by iLLiCiTiT** [comment]
> Nope still nothing.

So, if you'll add for example this item to any schema:
```
{
    "key": "something_something",
    "label": "Maya env test",
    "type": "raw-json",
    "env_group_key": "maya"
}
```
open settings gui, save values and then load:
```
from pype.api import environments


test_env = environments()
print(test_env["maya"])
```

The output is not what was saved in setting gui?

**Comment by mkolar** [comment]
Precisely. I tried with 
```
{
            "key": "ftrack_env_test",
            "label": "Ftrack Env Test",
            "type": "dict",
            "children": [{
                "key": "ftrack_env",
                "label": "Ftrack Environment",
                "type": "raw-json",
                "env_group_key": "ftrack_test"
            }
```

and then in nuke printing 
```
from pype.api import environments
print(environments()['ftrack_env'])
```

and it's not there. I've save the env before as default and tried as studio override as well. I can see it saved in the settings but it doesn't load back.

**Comment by iLLiCiTiT** [comment]
> and it's not there. I've save the env before as default and tried as studio override as well. I can see it saved in the settings but it doesn't load back.

Oh that's probably my fault, key is not store, but `env_group_key`, in your case it should be:
```
from pype.api import environments
print(environments()['ftrack_test'])
```

If it's too bizzar I can change `env_group_key` to boolean and `key` will be used as "group key"...

**Pull request merged**
