### PR TITLE
Config GUI

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
This PR is only GUI implementation. Requires to prepare schemas for settings in another PRs. Important is that `schema` is not meant as validation schema but as GUI schema, how widgets are used in GUI and how result data will be stored.

## Changes
- implementation of configuration GUI
- first version for testing

## TODO
- ~~value validations - do not allow to save if e.g. raw json is not in valid format~~
- new values - if default settings are missing new keys/values
    - these are shown as "modified" now, but I think it would be better to have different color for "new" values
- ~~default values from schema~~
- ~~additional attributes like min/max number, float decimal points~~
- ~~cancel override/modification~~
    - Now is not visualy visible that overrides were removed, can mark them as "modified" (blue) but that may be misleading
- ~~reapply overrides and modifications (after save)~~
- ~~list input is currently only for string (allow for all available inputs)~~
    - ~~list input does not load data properly~~
    - ~~list input does not even collect data properly, list with key "input" and value "input" is collected like:~~
- ~~raw json is not storing data properly~~
- ~~raw json is not validating properly changes and json format~~
- ~~load saved overrides the same way~~
- ~~overrides per different key than in schema~~ (This is not allowed - only "group" keys are overriden)
- add nullable values - How to visually show?
- allow to pop key - How to visually show?
- custom widgets
    - prepare abstract class for custom widgets
- guide widget
    - help guides from schema
- schema validations
    - ~~do not allow more than once `is_group` attribute se to true~~
    - ~~check that there are not key duplicates in schema under same key~~
    - ...
- style changes
- copy values
- ~~add Anatomy settings~~
- add Environments
...

## Requires:
pype-setup: https://github.com/pypeclub/pype-setup/pull/64
pype-config: https://github.com/pypeclub/pype-config/pull/78

### CODE REVIEW

**Comment by antirotor** [comment]
I propose to add new column to increase readability:
``` 
 ________________________________________________________________
|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  _ [] X|
|________________________________________________________________|
|  _____________    ________________    _______________________  |
| |             |  |                |  |                       | |
| | settings #1 |  | Option Grp1    |  | Option A              | |
| | settings #2 |  |   |-> Option A |  | --------------------- | |
| | settings #3 |  |   \-> Option B |  | Some control 1        | |
| | ...         |  | ...            |  | Some control 2        | |
| |_____________|  |________________|  |_______________________| |
|________________________________________________________________|
```
Middle one will provide simple tree structure that can reflect status of override, etc. leaving main control window visually uncluttered and simpler.

**Comment by iLLiCiTiT** [comment]
GUI schema has multiple input types. Each type has different possible keys that can be used to define look of input or output type.

**Comment by mkolar** [comment]
Can we please add:
- refresh button in the dev mode
- Rename all configurations to "settings"
- rename `input` to `item_type`

**Comment by iLLiCiTiT** [comment]
Must do:
- change `expandable` -> `collapsable` and `expanded` -> `collapsed`

Required item types:
- simple label (for notes etc.)
- enumerator (radio button or combobox)
- for environments
    - number

**Comment by iLLiCiTiT** [comment]
How to run Settings GUI:
- open CMD -> go to pyp-setup -> run `pype settings`
- to run in develop mode run `pype settings -d` or `pype settings --develop`
    - develop mode is meant for creating new schemas and setting default values

Example of input types:
- there is one schema for showing possibilities with implemented input types
- to show this schema go to `./pype/tools/settings/settings/gui_schemas/system_schema/0_system_gui_schema.json` by default there should be
```
{
    "key": "system",
    "type": "dict-invisible",
    "children": [
        {
            "type": "dict-invisible",
            "key": "global",
            "children": [{
                "type": "schema",
                "children": [
                    "1_tray_items",
                    "1_applications_gui_schema",
                    "1_tools_gui_schema",
                    "1_intents_gui_schema"
                ]
            }]
        }, {
            "type": "dict-invisible",
            "key": "muster",
            "children": [{
                "type": "dict-modifiable",
                "object_type": "number",
                "input_modifiers": {
                    "minimum": 0,
                    "maximum": 300
                },
                "is_group": true,
                "key": "templates_mapping",
                "label": "Muster - Templates mapping",
                "is_file": true
            }]
        }
    ]
}
```

Only what you need to do is to add new child under "system" key with "schema" type and schema name "1_examples".
Like:
```
{
    "key": "system",
    "type": "dict-invisible",
    "children": [
        {
            "type": "dict-invisible",
            "key": "global",
            "children": [{
                "type": "schema",
                "children": [
                    "1_tray_items",
                    "1_applications_gui_schema",
                    "1_tools_gui_schema",
                    "1_intents_gui_schema"
                ]
            }]
        }, {
            "type": "dict-invisible",
            "key": "muster",
            "children": [{
                "type": "dict-modifiable",
                "object_type": "number",
                "input_modifiers": {
                    "minimum": 0,
                    "maximum": 300
                },
                "is_group": true,
                "key": "templates_mapping",
                "label": "Muster - Templates mapping",
                "is_file": true
            }]
        }, {
            "type": "schema",
            "children": [
                "1_examples"
            ]
        }
    ]
}
```

**Comment by kalisp** [comment]
List of issues found on `pype-config/presets/plugins`:

> maya
>> `filter.json` - Should be implemented? ("Preset n1")
>> `load.json` - colors in format "model": [0.821, 0.518, 0.117] , I am guessing specific widget should be created ?
>>`workfile_build.json` - parent is array of dictionaries

>nuke
>> `publish.json` - nodes - list of lists without labels
>>`workfile_build.json` - parent is array of dictionaries

>nukestudio
>>`filter.json` - this seems to be disjunctive options, is there a widget for it?

>test - should be implemeted too? (Probably yes because of existing tests.)

**Pull request merged**
