### PR TITLE
Fusion basic integration

### PR DESCRIPTION
**Pull request by jezscha**
Adding basic launching methods and updating fusion integration from latest Colorbleed config repository
https://github.com/Colorbleed/colorbleed-config

Basic functionality:
- launchers in pype
- integrating pype menu into fusion scripts
- merging Colorbleed-config's fusion development 
- rendering locally or deadline
- creating, loading, inventory

Tested on Fusion 16 (licence) and Fusion 9 (free)

Testing this PR
A. Installing Fusion's own python 3.6 interpreter into path defined in `pype-config/environments/fusion.json:PYTHON36` . We are using Python 3.6.2

B. Installing PySide2 into python 3.6 for correct gui work:

As Pype is using PySide2 inside installation python 3.6 as it is explained above. Follow this step-by-step:
`C:\Python\Python36\python.exe -m pip install PySide2`

dependencies:
https://github.com/pypeclub/pype-config/pull/76

### CODE REVIEW

**Comment by jezscha** [comment]
Hi @BigRoy could you share with me what are the basic environment variables you are using in studio. Also I am not sure if you are actually using Fusionless any more as I don't see any imports of the code in colorbleed-config. Thank you.

**Comment by BigRoy** [comment]
We did indeed drop the use for Fusionless in core itself. I might still have it scattered throughout code of our config, not sure. :)

Regarding environment, I'd have to look that up but unfortunately I am out of office for a few weeks.

**Comment by jezscha** [comment]
> Also make sure the `acre` branch on colorbleed repo isn't more ahead with Fusion things. That's what we are using.

Good point, thank you. No worries about environment vars. We will be copying scripts into appropriate folder with pre-launch hook.

**Comment by mkolar** [comment]
Works. However and important point needs to be documented.

It requires python 3.6.x installation and environment variable `PYTHON36` pointed to it's location. And every user must have PySide2 installed in that python36 for this to work. Same problem as with Blender and Resolve.

**Review by mkolar — APPROVED** [review]

**Comment by BigRoy** [comment]
Are you sure the Python install needs to be local + that PySide2 needs to be local? At the very least I'm sure we are running PySide2 on the server for Fusion - and I believe Python too (but not sure...)

It does have the side-effect that it triggers the Qt UIs relatively slow as it loads Python+PySide2 over the network.

**Comment by mkolar** [comment]
@BigRoy you are right, they don't have to be local necessarily, however the speed penalty is quite substantial in certain scenarios we encountered. Also, we are generally getting ready with pype 3.0 to run fully locally for each user....Remote workflows rule the world nowadays :)

**Pull request merged**
