### PR TITLE
Apply Colorspace to Hiero project from presets

### PR DESCRIPTION
**Pull request by jezscha**
dependent PR:
https://github.com/pypeclub/pype-config/pull/93

- adding menu options for applying presets to project
- adding menu option for applying presets to project's clip with regex search pattern
- collecting project's colorspace attributes onto workfile instance

### CODE REVIEW

**Comment by mkolar** [comment]
I'm afraid this is not possible to review. It's seems to contain a lot of other commits. Probably because the target branch was no created from the same base.

**Comment by jezscha** [comment]
> I'm afraid this is not possible to review. It's seems to contain a lot of other commits. Probably because the target branch was no created from the same base.

did this fixed the problem?

**Comment by mkolar** [comment]
> did this fixed the problem?

yes perfect. Thank you

**Review by mkolar — COMMENTED** [review]
Project colorspace working great. I can't get it to apply to clips though. Maybe just misunderstanding the principle. 

I assume this should ensure correct colorspace on loaded clips via loader? Or should it ensure the colorspace on the clip for exporting? Just unsure how to use it, because I can't get it to change anything :)

**Comment by mkolar** [comment]
For the clips color:
This is the filepath I have loaded in the bin (using previously published plate from loader)
`C:/projects/milan_testing/sequences/sq1001/sq1001sh010/publish/plate/plateMain/v002/mln_sq1001sh010_plateMain_v002.%04d.exr`

This is the regex that should be catching it:  `[^-a-zA-Z0-9](plateMain).*(?=exr)` (default from the config PR)

When I change the color setting on the clip, and the `apply colorspace clips` does nothing (it should change to linear)
color_clips_hiero

**Pull request closed without merging**
