### PR TITLE
nuke render family

### PR DESCRIPTION
**Pull request by jezscha**
it was publishing with wrong family to files during render.local

### CODE REVIEW

**Comment by mkolar** [comment]
This will actually cause issues in running productions. Let's discuss tomorrow what could be done. Because we use main family in render publishing, anything that is already running this would go to different folders

**Comment by jezscha** [comment]
> This will actually cause issues in running productions. Let's discuss tomorrow what could be done. Because we use main family in render publishing, anything that is already running this would go to different folders

I am not sure if this has been understood correctly. Before it was publishing _render_ and _render.farm_ to `render2d` family folder  but _render.local_ to `write` family folder. Now it is unified and all are published to `render2d` folder.

**Comment by tokejepsen** [comment]
For backwards compatibility could we not have `write` family in `families`?

**Comment by jezscha** [comment]
> For backwards compatibility could we not have `write` family in `families`?

I this question to my comment or @mkolar 's? From the backward compatibility as I see it, we would need to have `write` family at first loading of write nodes until the moment when Collect_write is changing it to `render.local` or `render.farm`. I am perhaps missing something here. As I have seen this as simple fix of inconsistency but I see it is breaking a lot from your productions. Could anyone @mkolar or @tokejepsen be more specific on the topic?

**Comment by tokejepsen** [comment]
I think that when you have existing containers in your workfile with `write` family then updating will be an issue. But I might be wrong...

**Comment by jezscha** [comment]
> I think that when you have existing containers in your workfile with `write` family then updating will be an issue. But I might be wrong...

I am not changing any family and families in CreateWrite so I don't see an issue here. Only changed code you could see in this PR is done on CollectWrite and in created instance. This is only effecting all going downstream afterward. So if you had some inhouse validators/extractors checking family `write` it would effect those..

**Comment by mkolar** [comment]
What @tokejepsen means, and he is probably right, is that if you are running a project, which has previously published a shot as `write`, but after this change will publish it as as `render2d` there is a potential of not being able to update from the v02 of `write` to v03 of `render2d`.

Actually looking at it some more. There are more issues. 

1. We are using the main `family` as for filling the anatomy template.
2. We want all the renders to appear in the `render` folder in the publish
3. `render2d` and `render3d` are supposed to act as differentiators to help out with plugin filtering, but they should get exposed to the user at the end of the day.

So we should make sure that any rendered frames that we being published have `render` as the main family, rather than `write`, or `render2d` because the main family is eventually pushed through to the folder names and also loader filter. 

So really the key question is what do we want users to see these outputs as. `write`, `render2d` or `render`. We were using `render` consistently until a few PRs on multiple levels broke that, but I think we should aim at making sure, that is what we continue using for the users themselves. 

Secondly though if we do that. we need to somehow keep backwards compatibility within already running projects. Which could be done with a few tweaks to the project specific config.

**Pull request closed without merging**
