### PR TITLE
Bugfix/PYPE-768 blender launch from ftrack

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
- Please don't ask why and how

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
blender's __init__ was cleaned up from unused imports

**Comment by mkolar** [comment]
I'll be honest, this is mildly confusing :)

**Comment by iLLiCiTiT** [comment]
Yes, this helped:
```
popen = avalonlib.launch(
    executable=execfile, args=[], environment=env
)
```

**Comment by mkolar** [comment]
Not really. But that seems to be the fun of blender development :(.

So after some testing this, here are my findings.

1. I can't reproduce it NOT working with either `develop` or this branch when using `2.81`. Albeit the opening times seem a bit shorter and more consistent with this PR. Still super inconsistent though.

2. On the other hand, trying to run 2.82a, I have zero success of making it launch with avalon menu. From very brief analysis it seems like non of our environments apart from `pype-config/environments/blender.json` are surviving the launch of 2.82.

Man how I'm looking forward to LTS releases of Blender.

**Pull request merged**
