### PR TITLE
Igniter and Pype bootstrap improvements

### PR DESCRIPTION
**Pull request by antirotor**
## Feature

This refactor functions used to create and install Pype version via Igniter. Including few UI improvements and stopping `start.py` to load environments from settings until proper Pype version can be determined.

### CODE REVIEW

**Comment by robmoggach** [comment]
On first run would be great to have some more verbosity on documentation/tooltips... 
What is the studio root?
What is the repo url?
What is the mongo connection string?
Eg. `mongodb+srv://pype:<password>@db.studio.lan/pype`

> Further to that... (and OT) setting up DNS SRV records is always lovely for mongo

**Comment by mkolar** [comment]
The documentation will come once the beta is out. It was still changing quite a lot until now. 

mongo you got right
Repo URL is path to a folder where studio stores zips of pype version for arts

**Comment by antirotor** [comment]
Added option to run Pype without installation

**Comment by iLLiCiTiT** [comment]
## Issues I found out
- `~/igniter/tools.py` function `get_pype_path_from_db` expect that there is `"global_settings"` document in mongo
- directory in built pype  `"~/<build folder>/lib/"` is added to environment `PYTHONPATH` which breaks all python hosts as it overrides default python modules
- seems like startup scripts are not executed on host start (didn't look for a reason much)
   - **NOTE:** We set startup scripts to both avalon and pype paths which does not make sence as what happens in pype's startup should happen on avalon's host installation (which also install pype's host) or we should not start avalon's startup script at all. We should use avalon script or pype script, not both.

**Pull request merged**
