### PR TITLE
photoshop with websocket

### PR DESCRIPTION
**Pull request by kalisp**
**What's changed?**
Reiplementaion of Photoshop integration with websocket server and RPC, without com objects (eg. multiplatform).

Pype repo contains websocket server and implemented collectors and extractors.
Avalon-core contains basic api. Com objects and usage of http server were removed

Extension needs to be installed to Phostoshop manually first, see https://github.com/kalisp/avalon-core/blob/feature/photoshop_with_websocket/avalon/photoshop/README.md

Requires:
pype:pypeclub/avalon-core#179
pype-setup:pypeclub/pype-setup#65
pype-config:pypeclub/pype-config#79

### CODE REVIEW

**Comment by kalisp** [comment]
Fully implemented and available for testing.

**Comment by kalisp** [comment]
Yeah, thats weird. But it should be still working, as long as the original window is not closed, Photoshop will use the original window  as a communication path. I will try to figure out "force kill" of the server, I won't be able to close the window though, afaik.

**Comment by iLLiCiTiT** [comment]
> I will try to figure out "force kill" of the serve

Is possible to do it opposite way, to ask if server is already running?

**Comment by jezscha** [comment]
the problem with the server is still remaining. I believe this has to be solved as users will do this mistake. First they will close the photohop and ignore the console window. So then after new Photoshop window will be opened nothing will work.

```**Traceback (most recent call last):
  File "C:\CODE\pype-setup\repos\pype\pype\modules\websocket_server\websocket_server.py", line 166, in run
    self.loop.run_until_complete(self.start_server())
  File "C:\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\CODE\pype-setup\repos\pype\pype\modules\websocket_server\websocket_server.py", line 191, in start_server
    await self.site.start()
  File "C:\Users\Public\pype_env2\Lib\site-packages\aiohttp\web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "C:\Python\Python37\lib\asyncio\base_events.py", line 1374, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8099): only one usage of each socket address (protocol/network address/port) is normally permitted
>>> [ Websocket server stopped ]
INFO:WebsocketServer:Websocket server stopped**```

**Comment by kalisp** [comment]
I re-did closing implementation, fixed small issues that I could find. Please check.

**Comment by mkolar** [comment]
This is now working well and much faster than before. Please resolve conflict and we can merge

**Pull request merged**
