### PR TITLE
Draft/pyblish pype keep gui responsive

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Issue
- pyblish pype GUI is not responsive when plugin is processed

## Changes
- plugin processing is running in thread, until is finished the QtApplication.processEvents() is executed

## Notes
- tested only in standalone publisher, need testing in Nuke, Maya and other hosts

### CODE REVIEW

**Comment by jezscha** [comment]
I was testing Nuke 11.2v2 and it was crashing during publishing. I was testing responsiveness of the gui and it is much better except it is not finishing publishing so perhaps there is some problem with threading as it is telling me. 
image

**Comment by jezscha** [comment]
so now the error is the same
Not sure it it is something to do with the Nuke working with its own PySide2 or threading.. on python 2.7
image

**Comment by mkolar** [comment]
This causes the same problem in maya. any cmds call shut it down. Most likely due to not being executed in main thread as well

**Comment by mkolar** [comment]
I'm closing the PR for now, and putting it on hold. It's more trouble than it's worth in the light of other requirements

**Pull request closed without merging**
